AllCops:
  NewCops: enable
  Include:
  - "**/*.rb"
  - "**/*file"
  - "**/*.gemspec"
  Exclude:
  - "./vendor/**/*"
  SuggestExtensions: false

Layout/LineLength:
  Max: 160
Layout/EndOfLine:
  EnforcedStyle: lf

Lint/UnusedMethodArgument:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  AllowedMethods:
  - require
  - require_relative
  - fastlane_require
  - gem
  - program
  - command
  - raise
  - attr_accessor
  - attr_reader
  - desc
  - lane
  - private_lane
  - platform
  - to
  - not_to
  - describe
  - it
  - be
  - context
  - before
  - after

Naming/FileName:
  Exclude:
  - "**/Gemfile"
  - "**/Podfile"
  - "**/Rakefile"
  - "**/Fastfile"
  - "**/Pluginfile"
  - "**/*.gemspec"
Naming/PredicateName:
  Enabled: false

Metrics:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
Gemspec/DevelopmentDependencies:
  Enabled: false
